package si.inova.androidarchitectureplayground.network.services

import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonEncodingException
import si.inova.androidarchitectureplayground.common.exceptions.NoNetworkException
import si.inova.androidarchitectureplayground.common.exceptions.UnknownCauseException
import si.inova.androidarchitectureplayground.common.outcome.CauseException
import java.net.ConnectException
import java.net.SocketTimeoutException
import java.net.UnknownHostException

/**
 * Transform exception generated by retrofit into semantic [CauseException].
 */
fun Throwable.transformRetrofitException(): CauseException {
   return when (this) {
      is SocketTimeoutException, is ConnectException, is UnknownHostException -> NoNetworkException(cause = this)
      is JsonDataException, is JsonEncodingException -> JsonParsingException(cause = this)
      else -> UnknownCauseException(cause = this)
   }
}

class JsonParsingException(message: String? = null, cause: Throwable? = null) : CauseException(message, cause)
