[versions]
androidGradlePlugin = "8.1.4"
androidGradleCacheFix = "3.0"
androidx-activity-compose = "1.8.1"
androidx-core = "1.12.0"
androidx-compose-compiler = "1.5.4"
androidx-compose-runtime = "1.5.4"
androidx-compose-material3 = "1.1.2"
androidx-lifecycle = "2.6.2"
detekt = "1.23.3"
detekt-compilerWarnings = "0.0.4"
detekt-twitterCompose = "0.0.26"
kotlin = "1.9.20"
kotlin-immutableCollections = "0.3.6"
junit4 = "4.13.2"
junit4-parameterinjector = "1.12"
junit5 = "5.10.0"
kotlinova = "3.0.0-alpha19"
okhttp = "4.12.0"
orgJson = "20231013"
kotest = "5.7.2"
ksp = "1.9.20-1.0.14"
moduleGraphAssert = "2.5.0"
moshi = "1.15.0"
moshi-ir = "0.25.0"
retrofit = "2.9.0"
paparazzi = "1.3.1"
simpleStack = "2.8.0"
showkase = "1.0.2"
sqldelight = "2.0.0"
tomlj = "1.1.0"
turbine = "1.0.0"
versionsChecker = "0.49.0"

[libraries]
androidGradleCacheFix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version.ref = "androidGradleCacheFix" }
android-agp = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-runtime" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compilerWarnings = { module = "com.braisgabin.detekt:kotlin-compiler-wrapper", version.ref = "detekt-compilerWarnings" }
detekt-twitterCompose = { module = "com.twitter.compose.rules:detekt", version.ref = "detekt-twitterCompose" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
kotlin-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutableCollections" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
versionsCheckerPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsChecker" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
