[versions]
androidGradlePlugin = "8.5.1"
androidGradleCacheFix = "3.0.1"
androidx-activity-compose = "1.9.1"
androidx-core = "1.13.1"
androidx-core-splashscreen = "1.0.1"
# See https://developer.android.com/jetpack/androidx/releases/compose-kotlin
androidx-compose-compiler = "1.5.14"
androidx-compose-runtime = "1.6.8"
androidx-compose-material = "1.6.8"
androidx-compose-material3 = "1.2.1"
androidx-compose-tracing = "1.0.0-beta01"
androidx-datastore = "1.1.1"
androidx-lifecycle = "2.8.4"
androidx-benchmark = "1.2.4"
androidx-profileInstaller = "1.3.1"
androidx-test-ext = "1.2.1"
androidx-test-uiautomator = "2.3.0"
androidx-test-espresso = "3.6.1"
androidx-test-runner = "1.6.1"
androidx-test-orchestrator = "1.5.0"
androidx-perfetto = "1.0.0"
androidx-r8 = "8.5.35"
anvil = "2.5.0-beta07"
certificateTransparency = "2.5.49"
composeGuard = "2.3.2"
coil = "2.7.0"
dagger = "2.51.1"
desugarJdkLibs = "2.0.4"
detekt = "1.23.6"
detekt-compilerWarnings = "0.0.4"
detekt-compose = "0.4.8"
dependencyAnalysis = "1.33.0"
dispatch = "1.0.0-beta10"
keeperPlugin = "0.16.1"
kotlin = "1.9.24"
kotlin-coroutines = "1.8.1"
kotlin-immutableCollections = "0.3.7"
junit4 = "4.13.2"
junit4-parameterinjector = "1.16"
junit5 = "5.10.3"
kotlinova = "3.1.0"
okio = "3.9.0"
okhttp = "4.12.0"
orgJson = "20240303"
kotest = "5.9.1"
ksp = "1.9.24-1.0.20"
moduleGraphAssert = "2.6.0"
moshi = "1.15.1"
moshi-ir = "0.26.0"
retrofit = "2.11.0"
paparazzi = "1.3.3"
rebugger = "1.0.0-rc03"
simpleStack = "2.9.0"
showkase = "1.0.3"
tomlj = "1.1.1"
turbine = "1.1.0"
versionsChecker = "0.51.0"
whatTheStack = "1.0.0-alpha07"

[libraries]
androidGradleCacheFix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version.ref = "androidGradleCacheFix" }
android-agp = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-runtime" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-runtime" }
androidx-compose-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "androidx-compose-tracing" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-material3-sizeClasses = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidx-compose-material3" }
androidx-profileInstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileInstaller" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-test-junitRules = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidx-perfetto = { module = "androidx.tracing:tracing-perfetto", version.ref = "androidx-perfetto" }
androidx-perfetto-binary = { module = "androidx.tracing:tracing-perfetto-binary", version.ref = "androidx-perfetto" }
androidx-r8 = { module = "com.android.tools:r8", version.ref = "androidx-r8" }
anvil = { module = "com.squareup.anvil:gradle-plugin", version.ref = "anvil" }
anvil-api = { module = "com.squareup.anvil:compiler-api", version.ref = "anvil" }
anvil-utils = { module = "com.squareup.anvil:compiler-utils", version.ref = "anvil" }
certificateTransparency = { module = "com.appmattus.certificatetransparency:certificatetransparency", version.ref = "certificateTransparency" }
certificateTransparency-android = { module = "com.appmattus.certificatetransparency:certificatetransparency-android", version.ref = "certificateTransparency" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
composeGuard = { module = "com.joetr.compose.guard:com.joetr.compose.guard.gradle.plugin", version.ref = "composeGuard" }
dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dependencyAnalysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependencyAnalysis" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compilerWarnings = { module = "com.braisgabin.detekt:kotlin-compiler-wrapper", version.ref = "detekt-compilerWarnings" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
dispatch = { module = "com.rickbusarow.dispatch:dispatch-core", version.ref = "dispatch" }
dispatch-espresso = { module = "com.rickbusarow.dispatch:dispatch-android-espresso", version.ref = "dispatch" }
dispatch-test = { module = "com.rickbusarow.dispatch:dispatch-test", version.ref = "dispatch" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
junit4-parameterinjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "junit4-parameterinjector" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
keeperPlugin = { module = "com.slack.keeper:keeper", version.ref = "keeperPlugin" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutableCollections" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# Dummy entry, we don't need to actually use the stdlib explicitly, but it is used for the version checker to auto update kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinova-compose = { module = "si.inova.kotlinova:compose", version.ref = "kotlinova" }
kotlinova-navigation = { module = "si.inova.kotlinova:navigation", version.ref = "kotlinova" }
kotlinova-navigation-compiler = { module = "si.inova.kotlinova:navigation-compiler", version.ref = "kotlinova" }
kotlinova-navigation-detekt = { module = "si.inova.kotlinova:navigation-detekt", version.ref = "kotlinova" }
kotlinova-navigation-test = { module = "si.inova.kotlinova:navigation-test", version.ref = "kotlinova" }
kotlinova-compose-androidTest = { module = "si.inova.kotlinova:compose-android-test", version.ref = "kotlinova" }
kotlinova-core = { module = "si.inova.kotlinova:core", version.ref = "kotlinova" }
kotlinova-core-test = { module = "si.inova.kotlinova:core-test", version.ref = "kotlinova" }
kotlinova-retrofit = { module = "si.inova.kotlinova:retrofit", version.ref = "kotlinova" }
kotlinova-retrofit-test = { module = "si.inova.kotlinova:retrofit-test", version.ref = "kotlinova" }
kotlinova-gradle = { module = "si.inova.kotlinova:gradle", version.ref = "kotlinova" }
ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
moduleGraphAssert = { module = "com.jraska.module.graph.assertion:plugin", version.ref = "moduleGraphAssert" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-ir = { module = "dev.zacsweers.moshix:dev.zacsweers.moshix.gradle.plugin", version.ref = "moshi-ir" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
orgJson = { module = "org.json:json", version.ref = "orgJson" }
rebugger = { module = "io.github.theapache64:rebugger", version.ref = "rebugger" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
versionsCheckerPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsChecker" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
showkase = { module = "com.airbnb.android:showkase", version.ref = "showkase" }
showkase-processor = { module = "com.airbnb.android:showkase-processor", version.ref = "showkase" }
simpleStack = { module = "com.github.Zhuinden:simple-stack", version.ref = "simpleStack" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
whatTheStack = { module = "com.github.fvito:WhatTheStack", version.ref = "whatTheStack" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }


[plugins]
anvil = { id = "com.squareup.anvil", version.ref = "anvil" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
versionsChecker = { id = "com.github.ben-manes.versions", version.ref = "versionsChecker" }
